spring:
  datasource:
    url: jdbc:h2:mem:stat
    driver-class-name: org.h2.Driver
    username: stat
    password: stat
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      #http://localhost:8080/h2-console - зайти посмотреть что в БД
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:schema.sql

server:
  port: 9090